### ISSUE TITLE
Questions about the downstream application object classification.

### ISSUE THREAD

**Issue by YongjianDeng** [uzh-rpg/rpg_e2vid#10]
Hi,

I am wondering when you train the generator from ncars events to images, would you have to access the ncars GT images or just find some other source to be an alternative option. As far as i know, there are no ncars GT images kept in its official dataset website.

Best,

**Comment by supitalp** [comment]
Hi,
As far as I know there are no ground truth images available in the N-CARS dataset.
The image reconstructions from N-CARS event data in the paper were obtained as described in the paper, from synthetic event data generated with ESIM. The network was not specifically finetuned for car reconstruction.

**Comment by YongjianDeng** [comment]
Thanks for your response, how about caltech and nmnist dataset. When you trained the network, have you used the GT images from the conventional dataset or just use synthetic event data?

**Comment by supitalp** [comment]
No, all the results presented in the paper were obtained from the same network, trained only with synthetic event data. The N-Caltech and N-MNIST images were not used for training.

**Comment by YongjianDeng** [comment]
I appreciate your timely answer.

**Comment by Antleaf-0921** [comment]
> I appreciate your timely answer.
I encountered a similar issue with object classification. Could you kindly share your email so we can continue the discussion?
