### ISSUE TITLE
E2VID dataset corrupt

### ISSUE THREAD

**Issue by ya332** [uzh-rpg/rpg_e2vid#14]
The tar dataset file here http://rpg.ifi.uzh.ch/data/E2VID/models/E2VID_lightweight.pth.tar seems corrupted, or damaged. I can't open it. 
I am using Windows 10.

**Comment by magehrig** [comment]
I just executed the [example in the readme](https://github.com/uzh-rpg/rpg_e2vid#run) without issues. Pytorch can load the model as expected. Is this different for you?
