### ISSUE TITLE
Radom contrast thresholds

### ISSUE THREAD

**Issue by etiennedub** [uzh-rpg/rpg_e2vid#8]
Hi,
I work on a project with the same simulator but I have some domain adaptation problem beetween the synthetic data and the real one.
In the paper appendix C, you talk about random contrast threshold. Is it possible to know precisely which parameters is randomly sample and which values you are using ?

Thanks

**Comment by supitalp** [comment]
Hi,
Please find attached the script I used to generate the training data for E2VID using ESIM. It uses the contrast threshold randomization values mentioned in the paper. To use it you will also need to download the MSCOCO17 images.

[e2vid_data_generation_script.zip](https://github.com/uzh-rpg/rpg_e2vid/files/4184824/e2vid_data_generation_script.zip)

I hope that helps!

**Comment by etiennedub** [comment]
Thank you, that should help!
